# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3eeb2cfd2a80dac57566e8940d86152b1fadb640d035c1cc5c3a53247049e9160cf592b3b05bf0e6aa1f3da335bd6946d3b84a9452ae21ad89a8460d292d02ea

test:
  secret_key_base: 1bfd8b6750cf40202295b975bb109c2cf7e390db95362eedc3e2f91cd2daff896c6edfc6fe752107340b685609b6484ccf013c9bc215f7aea5c2d8e63a0cd9c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
